name: "mfpulse"
version: "0.1.0"
config-version: 2
profile: "mfpulse"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  mfpulse:
    staging:
      +materialized: view
    marts:
      +materialized: table
