// Stock source registry — the public contract for where stock intelligence comes from.
// Keep this list conservative: a URL being publicly viewable does not automatically grant
// bulk collection or redistribution rights. `collectionStatus` therefore describes what MF
// Pulse actually does, not what might technically be scrapable.

export const SOURCE_STATUS = {
  active: { label: "Active feed", tone: "pos", rank: 0 },
  ready: { label: "Ready to connect", tone: "accent", rank: 1 },
  reference: { label: "Direct reference", tone: "neutral", rank: 2 },
  review: { label: "Access review", tone: "warn", rank: 3 },
  licensed: { label: "Licence required", tone: "warn", rank: 4 },
};

export const STOCK_SOURCES = [
  {
    id: "nifty50-constituents",
    name: "NIFTY 50 constituent file",
    publisher: "NSE Indices",
    authority: "index_provider",
    category: "Index universe",
    url: "https://nsearchives.nseindia.com/content/indices/ind_nifty50list.csv",
    format: "Official CSV",
    frequency: "Check daily; changes are event-driven",
    collectionStatus: "active",
    investorValue: "Canonical company name, NSE symbol, industry and ISIN for the current NIFTY 50 universe.",
    usePolicy: "Store constituent facts with retrieval date and source link; do not imply live index weights.",
  },
  {
    id: "bse100-constituents",
    name: "BSE 100 constituents",
    publisher: "BSE Indices",
    authority: "index_provider",
    category: "Index universe",
    url: "https://www.bseindices.com/indices-details/code/22/",
    format: "Official constituent page",
    frequency: "Check daily; changes are event-driven",
    collectionStatus: "active",
    investorValue: "Official membership of the 100-company BSE 100 universe (the product universe requested as ‘Sensex 100’).",
    usePolicy: "Store a dated constituent-metadata snapshot and link the official page; refresh remains manually reviewed while reuse terms are documented.",
  },
  {
    id: "nse-equity-master",
    name: "Securities available for equity trading",
    publisher: "NSE India",
    authority: "exchange",
    category: "Security identifiers",
    url: "https://www.nseindia.com/static/market-data/securities-available-for-trading",
    format: "Official CSV security master",
    frequency: "Daily verification",
    collectionStatus: "active",
    investorValue: "Verified NSE symbol and ISIN mapping used to reconcile BSE 100 companies without guessing tickers.",
    usePolicy: "Accept only unique normalized company-name matches, retain the source checksum and leave ambiguous identifiers empty.",
  },
  {
    id: "sebi-corporate-filings",
    name: "Corporate filings directory",
    publisher: "SEBI",
    authority: "regulator",
    category: "Regulation",
    url: "https://www.sebi.gov.in/curation/corporate_filings.html",
    format: "Official regulator directory to NSE and BSE filing records",
    frequency: "Reference directory",
    collectionStatus: "reference",
    investorValue: "A regulator-maintained map to governance, shareholding, BRSR, results, complaints, voting and other listed-company disclosures.",
    usePolicy: "Use the regulator directory to discover the correct primary filing class; preserve the exchange filing URL and publication date.",
  },
  {
    id: "nse-announcements",
    name: "Corporate announcements",
    publisher: "NSE India",
    authority: "exchange",
    category: "Exchange filings",
    url: "https://www.nseindia.com/companies-listing/corporate-filings-announcements?tabIndex=equity",
    format: "Official filing directory with attachments",
    frequency: "Event-driven",
    collectionStatus: "reference",
    investorValue: "Results, board decisions, management changes, orders, capital raising and other company disclosures.",
    usePolicy: "Facts and links only until an approved structured-access contract is documented.",
  },
  {
    id: "nse-results",
    name: "Financial results",
    publisher: "NSE India",
    authority: "exchange",
    category: "Financial statements",
    url: "https://www.nseindia.com/companies-listing/corporate-filings-financial-results",
    format: "Official filings and XBRL/attachments",
    frequency: "Quarterly and event-driven",
    collectionStatus: "reference",
    investorValue: "Primary-source quarterly and annual financial results.",
    usePolicy: "Normalize reported facts while retaining filing date, period, units, restatements and document URL.",
  },
  {
    id: "nse-shareholding",
    name: "Shareholding patterns",
    publisher: "NSE India",
    authority: "exchange",
    category: "Ownership",
    url: "https://www.nseindia.com/companies-listing/corporate-filings-shareholding-pattern",
    format: "Official filing directory",
    frequency: "Quarterly",
    collectionStatus: "reference",
    investorValue: "Promoter, institutional and public ownership disclosures.",
    usePolicy: "Always show the reporting period; never present an old pattern as current.",
  },
  {
    id: "bse-announcements",
    name: "Corporate announcements",
    publisher: "BSE India",
    authority: "exchange",
    category: "Exchange filings",
    url: "https://www.bseindia.com/corporates/ann.html",
    format: "Official filing directory with attachments",
    frequency: "Event-driven",
    collectionStatus: "reference",
    investorValue: "A second exchange record for disclosures, including BSE-only securities and cross-checking.",
    usePolicy: "Facts and links only until an approved structured-access contract is documented.",
  },
  {
    id: "company-ir",
    name: "Company investor-relations pages",
    publisher: "Each covered company",
    authority: "company_primary",
    category: "Company documents",
    url: null,
    format: "Per-company annual reports, presentations, transcripts and press releases",
    frequency: "Event-driven; quarterly review",
    collectionStatus: "ready",
    investorValue: "Management commentary and the original documents behind results, strategy, capital allocation and risks.",
    usePolicy: "Maintain one verified IR URL per company; extract facts and short summaries, link to the original, and do not republish full documents.",
  },
  {
    id: "sebi-rss",
    name: "Press releases and regulatory updates",
    publisher: "SEBI",
    authority: "regulator",
    category: "Regulation",
    url: "https://www.sebi.gov.in/sebirss.xml",
    format: "Official RSS",
    frequency: "Every three hours",
    collectionStatus: "active",
    investorValue: "Regulatory actions and market-structure changes from the primary regulator.",
    usePolicy: "Headline, summary, timestamp and source link with deterministic relevance rules.",
  },
  {
    id: "rbi-rss",
    name: "Press releases",
    publisher: "Reserve Bank of India",
    authority: "regulator",
    category: "Macro and banking",
    url: "https://www.rbi.org.in/pressreleases_rss.xml",
    format: "Official RSS",
    frequency: "Every three hours",
    collectionStatus: "active",
    investorValue: "Monetary policy, banking, liquidity and macro-financial announcements.",
    usePolicy: "Headline, summary, timestamp and source link with deterministic relevance rules.",
  },
  {
    id: "rbi-dbie",
    name: "Database on Indian Economy",
    publisher: "Reserve Bank of India",
    authority: "regulator",
    category: "Macro and banking",
    url: "https://data.rbi.org.in/",
    format: "Official statistical database and downloads",
    frequency: "Daily to annual, depending on series",
    collectionStatus: "reference",
    investorValue: "Rates, inflation, credit, liquidity, banking, payments and macro series for sector context.",
    usePolicy: "Store the series identifier, observation date, release date, unit and original RBI link; never mix different vintages silently.",
  },
  {
    id: "wikidata-company-identities",
    name: "Company identity and descriptive profiles",
    publisher: "Wikidata",
    authority: "open_knowledge",
    category: "Company profiles",
    url: "https://www.wikidata.org/wiki/Wikidata:Data_access",
    format: "CC0 structured knowledge graph",
    frequency: "Dated snapshot; reviewed on universe refresh",
    collectionStatus: "active",
    investorValue: "Short company descriptions, official websites and founding dates for entities that can be reconciled to the official universe by ISIN.",
    usePolicy: "Accept ISIN-verified entities only, retain QID and retrieval date, and fall back to official index classification when no match exists.",
  },
  {
    id: "mospi-statistics",
    name: "National accounts, IIP and price statistics",
    publisher: "Ministry of Statistics and Programme Implementation",
    authority: "government_data",
    category: "Sector and economy",
    url: "https://www.mospi.gov.in/",
    format: "Official releases and statistical downloads",
    frequency: "Monthly to annual",
    collectionStatus: "reference",
    investorValue: "Demand, production, inflation and economic context for sector research and scenario assumptions.",
    usePolicy: "Record series, unit, base year, period and release vintage; do not splice rebased series silently.",
  },
  {
    id: "cea-power-data",
    name: "Power-sector reports and statistics",
    publisher: "Central Electricity Authority",
    authority: "government_data",
    category: "Sector and economy",
    url: "https://cea.nic.in/",
    format: "Official reports and downloads",
    frequency: "Daily to annual, depending on report",
    collectionStatus: "reference",
    investorValue: "Installed capacity, generation, PLF, demand and fuel context for utilities and power producers.",
    usePolicy: "Use dated official releases and preserve plant/region scope and units.",
  },
  {
    id: "ppac-energy-data",
    name: "Petroleum planning and market statistics",
    publisher: "Petroleum Planning & Analysis Cell",
    authority: "government_data",
    category: "Sector and economy",
    url: "https://ppac.gov.in/",
    format: "Official dashboards, reports and downloads",
    frequency: "Weekly to monthly",
    collectionStatus: "reference",
    investorValue: "Consumption, prices, imports, refining and product-market context for oil and gas companies.",
    usePolicy: "Retain product, unit, period and publication date; distinguish provisional from final data.",
  },
  {
    id: "trai-telecom-data",
    name: "Telecom performance indicators",
    publisher: "Telecom Regulatory Authority of India",
    authority: "regulator",
    category: "Sector and economy",
    url: "https://www.trai.gov.in/",
    format: "Official reports and releases",
    frequency: "Monthly and quarterly",
    collectionStatus: "reference",
    investorValue: "Subscribers, market share, usage, quality and industry revenue context for telecom research.",
    usePolicy: "Preserve service area, period and definition; never compare unlike subscriber measures.",
  },
  {
    id: "irdai-insurance-data",
    name: "Insurance statistics and regulatory filings",
    publisher: "Insurance Regulatory and Development Authority of India",
    authority: "regulator",
    category: "Sector and economy",
    url: "https://irdai.gov.in/",
    format: "Official statistics, reports and circulars",
    frequency: "Monthly to annual",
    collectionStatus: "reference",
    investorValue: "Premium, claims, product mix, market structure and solvency context for insurers.",
    usePolicy: "Keep insurer, product, reporting period and metric definition attached to every observation.",
  },
  ...[
    ["et-markets", "Economic Times — Markets", "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms"],
    ["et-economy", "Economic Times — Economy", "https://economictimes.indiatimes.com/news/economy/rssfeeds/1373380680.cms"],
    ["mint-markets", "Mint — Markets", "https://www.livemint.com/rss/markets"],
    ["cnbctv18-markets", "CNBC-TV18 — Markets", "https://www.cnbctv18.com/commonfeeds/v1/cne/rss/market.xml"],
    ["ndtv-profit", "NDTV Profit — Latest", "https://feeds.feedburner.com/ndtvprofit-latest"],
    ["businessline-markets", "BusinessLine — Markets", "https://www.thehindubusinessline.com/markets/?service=rss"],
  ].map(([id, name, url]) => ({
    id,
    name,
    publisher: name.split(" — ")[0],
    authority: "business_media",
    category: "Market news",
    url,
    format: "Publisher RSS",
    frequency: "Every three hours",
    collectionStatus: "active",
    investorValue: "Timely reporting and context around companies, sectors, earnings and markets.",
    usePolicy: "Store headline, supplied summary, timestamp and link only; the publisher remains the reading destination.",
  })),
  {
    id: "bse-self-data-feed",
    name: "BSE Self Data Feed",
    publisher: "BSE India",
    authority: "exchange",
    category: "Market data",
    url: "https://marketdata.bseindia.com/",
    format: "Contracted exchange API/data delivery",
    frequency: "Per selected plan",
    collectionStatus: "licensed",
    investorValue: "Exchange-verified equity prices, delayed data, corporate data and index OHLC under an explicit plan and agreement.",
    usePolicy: "Connect only after the selected plan permits MF Pulse storage, display and end-user redistribution.",
  },
  {
    id: "nse-eod-history",
    name: "End-of-day and historical market data",
    publisher: "NSE Data & Analytics",
    authority: "exchange",
    category: "Market data",
    url: "https://www.nseindia.com/static/market-data/eod-historical-data-subscription",
    format: "Contracted SFTP/online historical product",
    frequency: "Daily / historical backfill",
    collectionStatus: "licensed",
    investorValue: "Official security and trade history suitable for long-range charts once contracted for the intended display use.",
    usePolicy: "Retain the agreement, adjustment policy and entitlement metadata; do not imply total return from unadjusted close prices.",
  },
  {
    id: "licensed-prices",
    name: "Live and delayed prices, index values and corporate-action adjusted history",
    publisher: "Exchange-authorised market-data vendor",
    authority: "licensed_vendor",
    category: "Market data",
    url: null,
    format: "Licensed API/feed",
    frequency: "Per contract",
    collectionStatus: "licensed",
    investorValue: "Reliable prices, adjusted histories, valuation snapshots and portfolio marking from an approved exchange-authorised vendor.",
    usePolicy: "Do not collect or display until a contract explicitly covers end-user redistribution.",
  },
];

export function getStockSourceSummary(sources = STOCK_SOURCES) {
  return sources.reduce(
    (summary, source) => {
      summary.total += 1;
      summary[source.collectionStatus] = (summary[source.collectionStatus] || 0) + 1;
      summary.categories.add(source.category);
      return summary;
    },
    { total: 0, active: 0, ready: 0, reference: 0, review: 0, licensed: 0, categories: new Set() }
  );
}

export function groupedStockSources(sources = STOCK_SOURCES) {
  return [...sources]
    .sort((a, b) => SOURCE_STATUS[a.collectionStatus].rank - SOURCE_STATUS[b.collectionStatus].rank || a.publisher.localeCompare(b.publisher))
    .reduce((groups, source) => {
      (groups[source.category] ||= []).push(source);
      return groups;
    }, {});
}
