"use client";

import InvestShell, { ButtonLink, Card, StatusPill } from "./InvestShell";
import { ErrorCard, LoadingCards, useInvestData } from "./useInvestData";

const copy = {
  mobile: ["Mobile verified", "Protects account access and transaction updates.", "2 min"], email: ["Email verified", "Receipts and important service communication.", "2 min"],
  pan: ["PAN verification", "Required for identity and tax reporting.", "3 min"], identity: ["Identity check", "Confirms your KYC status with recorded consent.", "5 min"],
  nominee: ["Nominee", "Helps your investments reach the right person.", "4 min"], bank: ["Bank verification", "Confirms where redemptions and mandates belong.", "4 min"],
  fatca: ["FATCA declaration", "A required tax-residency declaration.", "2 min"], pep: ["PEP screening", "A required regulatory declaration. Most investors answer no.", "1 min"],
  risk_profile: ["Risk profile", "Aligns products with your capacity and experience.", "5 min"],
  investment_ready: ["Investment ready", "Unlocked automatically when every required check is complete.", "Automatic"],
};

export default function ComplianceCenter() {
  const { data, loading, error, refresh } = useInvestData();
  const c = data?.compliance;
  const execution = data?.execution;
  const items = [...(c?.items || [])].sort((a,b) => Object.keys(copy).indexOf(a.item_key) - Object.keys(copy).indexOf(b.item_key));
  const next = items.find(i => !["verified","completed"].includes(i.status) && i.item_key !== "investment_ready");
  return <InvestShell eyebrow="Investment readiness" title={`${c?.percent || 0}% investor ready`} description="Two independent gates protect every transaction: your investor checks and MF Pulse's production execution controls." actions={<ButtonLink href={next ? `/invest/onboarding?step=${next.item_key}` : "/invest"}>{next ? "Continue next step" : "Return to overview"}</ButtonLink>}>
    {loading ? <LoadingCards /> : error ? <ErrorCard message={error} retry={refresh} /> : <>
      <Card className="overflow-hidden p-6 sm:p-8"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-accent">Your investor checks</div><div className="mt-3 flex items-center justify-between text-sm"><span className="font-semibold text-ink">{c.completed} of {c.total} checks complete</span><StatusPill status={c.overallStatus} /></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-surface-2"><div className="h-full rounded-full bg-accent" style={{width:`${c.percent}%`}} /></div><p className="mt-3 text-xs text-ink-faint">Estimated time remaining depends on provider review. You can save and resume safely.</p></div><div className="rounded-2xl bg-pos/10 px-5 py-4 text-center"><div className="text-2xl font-semibold text-pos">{c.percent}%</div><div className="text-[10px] font-bold uppercase tracking-[.12em] text-pos">Investor readiness</div></div></div></Card>
      <div className="mt-5 grid gap-3">
        {items.map((item, index) => { const meta = copy[item.item_key] || [item.item_key,"Required check","A few minutes"]; const done = ["verified","completed"].includes(item.status); return <Card key={item.item_key} className="p-4 sm:p-5"><div className="flex gap-4"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-full text-sm font-bold ${done ? "bg-pos text-white" : "bg-surface-2 text-ink-muted"}`}>{done ? "✓" : index + 1}</div><div className="min-w-0 flex-1 sm:flex sm:items-center sm:justify-between sm:gap-6"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-ink">{meta[0]}</h2><StatusPill status={item.status} /></div><p className="mt-1 text-sm leading-6 text-ink-muted">{meta[1]}</p>{item.rejection_reason && <p className="mt-2 text-xs font-medium text-neg">{item.rejection_reason}</p>}</div><div className="mt-3 flex shrink-0 items-center gap-4 sm:mt-0"><span className="text-xs text-ink-faint">{meta[2]}</span>{!done && item.item_key !== "investment_ready" && <a href={`/invest/onboarding?step=${item.item_key}`} className="text-sm font-semibold text-accent">Open →</a>}</div></div></div></Card>})}
      </div>
      <Card className="mt-8 overflow-hidden p-6 sm:p-8">
        <div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-warn">MF Pulse platform controls</div><h2 className="mt-2 text-2xl font-semibold text-ink">{execution?.liveExecutionReady ? "Production execution verified" : "Live execution is locked"}</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{execution?.message || "Checking production execution controls…"}</p><p className="mt-3 text-xs leading-5 text-ink-faint">ARN/EUIN attribution is for Regular plans. Direct-plan execution requires a separately registered direct/EOP route.</p></div><div className="min-w-44 rounded-2xl bg-warn/10 px-5 py-4 text-center"><div className="text-2xl font-semibold text-warn">{execution ? `${execution.completed}/${execution.total}` : "—"}</div><div className="text-[10px] font-bold uppercase tracking-[.12em] text-warn">Controls verified</div></div></div>
        {execution?.distributor ? <dl className="mt-5 grid gap-3 rounded-2xl bg-surface-2 p-4 text-xs sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-ink-faint">Distributor</dt><dd className="mt-1 font-semibold text-ink">{execution.distributor.name || "Not recorded"}</dd></div><div><dt className="text-ink-faint">ARN</dt><dd className="mt-1 font-semibold text-ink">{execution.distributor.arn || "Not recorded"}</dd></div><div><dt className="text-ink-faint">EUIN</dt><dd className="mt-1 font-semibold text-ink">{execution.distributor.euin || "Not recorded"}</dd></div><div><dt className="text-ink-faint">ARN valid until</dt><dd className="mt-1 font-semibold text-ink">{execution.distributor.arnValidUntil || "Expiry not recorded"}</dd></div></dl> : null}
        <div className="mt-5 grid gap-3 lg:grid-cols-2">{(execution?.controls || []).map((control) => <div key={control.id} className="rounded-2xl border border-line p-4"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-semibold text-ink">{control.label}</h3><StatusPill status={control.status} /></div><p className="mt-2 text-xs leading-5 text-ink-muted">{control.detail}</p></div>)}</div>
        <div className="mt-6 border-t border-line pt-5"><h3 className="text-sm font-semibold text-ink">Official framework and operating sources</h3><div className="mt-3 flex flex-wrap gap-2">{(execution?.sources || []).map((source) => <a key={source.id} href={source.url} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center rounded-full border border-line px-3.5 text-xs font-semibold text-ink-muted hover:border-accent/40 hover:text-ink">{source.publisher}: {source.label} ↗</a>)}</div><p className="mt-4 text-xs leading-5 text-ink-faint">This is an operational readiness checklist aligned to the cited sources, not a substitute for approval from AMFI, the selected transaction platform, AMCs, or qualified legal and compliance professionals.</p></div>
      </Card>
      <p className="mx-auto mt-6 max-w-2xl text-center text-xs leading-5 text-ink-faint">The current KYC, document, payment and investment adapters remain in mock mode. The production gate prevents them from moving money or units.</p>
    </>}
  </InvestShell>;
}
