"use client";

import { useEffect, useMemo, useState } from "react";
import InvestShell, { ButtonLink, Card, StatusPill } from "./InvestShell";
import { documentsApi } from "../../lib/invest/api";

const categories = ["all", "kyc", "statement", "tax", "mandate", "confirmation"];
function normalize(document) {
  return { ...document, id: document.id || document.document_id, name: document.name || document.file_name || document.title || "Untitled document", category: String(document.category || document.document_type || "other").toLowerCase(), updatedAt: document.updatedAt || document.updated_at || document.created_at, previewUrl: document.previewUrl || document.preview_url, downloadUrl: document.downloadUrl || document.download_url };
}

export default function DocumentVault() {
  const [documents, setDocuments] = useState([]); const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [errorCode, setErrorCode] = useState(""); const [downloading, setDownloading] = useState("");
  async function load() { setLoading(true); setError(""); setErrorCode(""); try { const value = await documentsApi.list(); setDocuments(Array.isArray(value.documents) ? value.documents.map(normalize) : []); } catch (err) { setError(err.message); setErrorCode(err.code || "unknown"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => documents.filter(document => { const matchesCategory = category === "all" || document.category === category; const haystack = (document.name + " " + document.category + " " + (document.tags || "")).toLowerCase(); return matchesCategory && haystack.includes(query.trim().toLowerCase()); }), [documents, category, query]);
  async function download(document) { if (document.downloadUrl) { window.open(document.downloadUrl, "_blank", "noopener,noreferrer"); return; } if (!document.id) return; setDownloading(document.id); try { const result = await documentsApi.download(document.id); if (result?.url) window.open(result.url, "_blank", "noopener,noreferrer"); else setError("This document is available, but a download link was not supplied."); } catch (err) { setError(err.message); } finally { setDownloading(""); } }
  const filtered = Boolean(query || category !== "all");
  return <InvestShell title="Your documents, in order." description="A secure, source-aware vault for statements, KYC records, tax reports and confirmations." actions={<ButtonLink href="/portfolio" secondary>Import a statement</ButtonLink>}>
    <div className="mb-5 grid gap-3 rounded-[1.4rem] border border-line bg-surface p-3 sm:grid-cols-[1fr_190px_auto]"><label><span className="sr-only">Search documents</span><input value={query} onChange={event => setQuery(event.target.value)} className="min-h-11 w-full rounded-xl bg-surface-2 px-4 text-sm text-ink outline-none focus:ring-2 focus:ring-accent/20" placeholder="Search documents…" /></label><label><span className="sr-only">Filter documents by category</span><select value={category} onChange={event => setCategory(event.target.value)} className="min-h-11 w-full rounded-xl border border-line bg-surface px-3 text-sm capitalize text-ink">{categories.map(value => <option key={value} value={value}>{value === "all" ? "All categories" : value}</option>)}</select></label><button type="button" onClick={load} className="min-h-11 rounded-xl border border-line px-4 text-sm font-semibold text-ink">Refresh</button></div>
    <div className="mb-5 flex items-center justify-between gap-3 text-xs text-ink-faint"><span>{loading ? "Checking secure vault…" : visible.length + " document" + (visible.length === 1 ? "" : "s")}</span><span className="inline-flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-pos" aria-hidden="true" />Encrypted workspace</span></div>
    {loading ? <div className="grid gap-3" role="status" aria-label="Loading document vault" aria-busy="true">{[1,2,3].map(value => <div key={value} className="skeleton h-28 rounded-[1.5rem]" />)}</div> : error && errorCode !== "not_found" ? <Card className="p-6" role="alert"><h2 className="font-semibold text-ink">The vault could not load</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{error}</p><button type="button" onClick={load} className="mt-4 min-h-11 rounded-full bg-ink px-5 text-sm font-semibold text-bg">Try again</button></Card> : visible.length === 0 ? <Card className="grid min-h-72 place-items-center p-7 text-center"><div className="max-w-md"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-accent/10 text-xl text-accent" aria-hidden="true">▤</div><h2 className="mt-5 text-lg font-semibold text-ink">{error ? "Your vault is ready to connect" : filtered ? "No matching documents" : "Your vault is empty"}</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{error ? "Document storage is not connected yet. Once the secure API is available, documents will appear here without a UI change." : filtered ? "Try another search or clear the category filter." : "Statements, KYC records and confirmations will appear here when the document service supplies them."}</p>{filtered && <button type="button" onClick={() => { setQuery(""); setCategory("all"); }} className="mt-5 min-h-11 rounded-full border border-line px-5 text-sm font-semibold text-ink">Clear filters</button>}</div></Card> : <div className="grid gap-3">{visible.map(document => <Card key={document.id || document.name} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="break-words font-semibold text-ink">{document.name}</h2><StatusPill status={document.status || "available"} /></div><p className="mt-2 text-xs capitalize text-ink-faint">{document.category} · {document.updatedAt ? new Date(document.updatedAt).toLocaleDateString("en-IN") : "Date unavailable"}</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={!document.previewUrl} onClick={() => document.previewUrl && window.open(document.previewUrl, "_blank", "noopener,noreferrer")} className="min-h-10 rounded-full border border-line px-4 text-xs font-semibold text-ink disabled:cursor-not-allowed disabled:opacity-40">Preview</button><button type="button" disabled={downloading === document.id} onClick={() => download(document)} className="min-h-10 rounded-full bg-ink px-4 text-xs font-semibold text-bg disabled:opacity-50">{downloading === document.id ? "Preparing…" : "Download"}</button></div></div><div className="mt-4 flex flex-wrap gap-3 text-[11px] text-ink-faint"><span>Source: secure document service</span><span>•</span><span>Archive and sharing controls appear when permitted</span></div></Card>)}</div>}
  </InvestShell>;
}
