"use client";

import { useEffect, useMemo, useState } from "react";
import InvestShell, { ButtonLink, Card, StatusPill } from "./InvestShell";
import { documentsApi } from "../../lib/invest/api";

const categories = ["all", "identity", "compliance", "portfolio", "transactions", "statements", "tax", "mandates", "other"];
const normalize = document => ({ ...document, id: document.id || document.document_id, name: document.name || document.title || document.file_name || "Untitled document", category: String(document.category || "other").toLowerCase(), updatedAt: document.updatedAt || document.updated_at || document.created_at });
const formatDate = value => value ? new Date(value).toLocaleString("en-IN") : "Time unavailable";

export default function DocumentVault() {
  const [documents, setDocuments] = useState([]); const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [downloading, setDownloading] = useState(""); const [selected, setSelected] = useState(null); const [detailsLoading, setDetailsLoading] = useState(false); const [notice, setNotice] = useState("");
  async function load() { setLoading(true); setError(""); try { const value = await documentsApi.list(); setDocuments(Array.isArray(value.documents) ? value.documents.map(normalize) : []); } catch (err) { setError(err.message || "The document vault could not load."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => documents.filter(document => (category === "all" || document.category === category) && `${document.name} ${document.category} ${(document.tags || []).join(" ")}`.toLowerCase().includes(query.trim().toLowerCase())), [documents, category, query]);
  async function showDetails(document) { setSelected({ document }); setDetailsLoading(true); try { const value = await documentsApi.details(document.id); setSelected({ document: normalize(value.document || document), timeline: value.timeline || [] }); } catch (err) { setNotice(err.message || "Document history is unavailable."); } finally { setDetailsLoading(false); } }
  async function download(document) { setDownloading(document.id); setNotice(""); try { const result = await documentsApi.download(document.id); setNotice(`Download activity recorded for “${document.name}”. Binary delivery will be enabled when storage is connected.`); if (result?.document) setDocuments(current => current.map(item => item.id === document.id ? normalize(result.document) : item)); } catch (err) { setError(err.message || "This document could not be prepared."); } finally { setDownloading(""); } }
  async function archive(document) { try { const result = await documentsApi.archive(document.id); setDocuments(current => current.map(item => item.id === document.id ? normalize(result.document || { ...item, status: "archived" }) : item)); setNotice(`“${document.name}” has been archived.`); } catch (err) { setError(err.message || "This document could not be archived."); } }
  const filtered = Boolean(query || category !== "all");
  return <InvestShell title="Your documents, in order." description="A secure, source-aware vault for statements, KYC records, tax reports and confirmations." actions={<ButtonLink href="/portfolio" secondary>Import a statement</ButtonLink>}>
    {notice && <p role="status" className="mb-5 rounded-2xl bg-pos/10 p-4 text-sm leading-6 text-pos">{notice}</p>}
    <div className="mb-5 grid gap-3 rounded-[1.4rem] border border-line bg-surface p-3 sm:grid-cols-[1fr_190px_auto]"><label><span className="sr-only">Search documents</span><input value={query} onChange={event => setQuery(event.target.value)} className="min-h-11 w-full rounded-xl bg-surface-2 px-4 text-sm text-ink outline-none focus:ring-2 focus:ring-accent/20" placeholder="Search documents…" /></label><label><span className="sr-only">Filter documents by category</span><select value={category} onChange={event => setCategory(event.target.value)} className="min-h-11 w-full rounded-xl border border-line bg-surface px-3 text-sm capitalize text-ink">{categories.map(value => <option key={value} value={value}>{value === "all" ? "All categories" : value}</option>)}</select></label><button type="button" onClick={load} className="min-h-11 rounded-xl border border-line px-4 text-sm font-semibold text-ink">Refresh</button></div>
    <div className="mb-5 flex items-center justify-between gap-3 text-xs text-ink-faint"><span>{loading ? "Checking secure vault…" : `${visible.length} document${visible.length === 1 ? "" : "s"}`}</span><span><span className="mr-2 inline-block h-2 w-2 rounded-full bg-pos" aria-hidden="true" />Encrypted workspace</span></div>
    {loading ? <div className="grid gap-3" role="status" aria-label="Loading document vault" aria-busy="true">{[1, 2, 3].map(value => <div key={value} className="skeleton h-28 rounded-[1.5rem]" />)}</div> : error ? <Card className="p-6" role="alert"><h2 className="font-semibold text-ink">The vault could not load</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{error}</p><button type="button" onClick={load} className="mt-4 min-h-11 rounded-full bg-ink px-5 text-sm font-semibold text-bg">Try again</button></Card> : visible.length === 0 ? <Card className="grid min-h-72 place-items-center p-7 text-center"><div className="max-w-md"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-accent/10 text-xl text-accent" aria-hidden="true">▤</div><h2 className="mt-5 text-lg font-semibold text-ink">{filtered ? "No matching documents" : "Your vault is empty"}</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{filtered ? "Try another search or clear the category filter." : "Statements, KYC records and confirmations will appear here when the document service supplies them."}</p>{filtered && <button type="button" onClick={() => { setQuery(""); setCategory("all"); }} className="mt-5 min-h-11 rounded-full border border-line px-5 text-sm font-semibold text-ink">Clear filters</button>}</div></Card> : <div className="grid gap-3">{visible.map(document => <Card key={document.id || document.name} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="break-words font-semibold text-ink">{document.name}</h2><StatusPill status={document.status || "generated"} /></div><p className="mt-2 text-xs capitalize text-ink-faint">{document.category} · {formatDate(document.updatedAt)}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => showDetails(document)} className="min-h-10 rounded-full border border-line px-4 text-xs font-semibold text-ink">Details</button><button type="button" disabled={downloading === document.id} onClick={() => download(document)} className="min-h-10 rounded-full bg-ink px-4 text-xs font-semibold text-bg disabled:opacity-50">{downloading === document.id ? "Recording…" : "Download"}</button>{document.status !== "archived" && <button type="button" onClick={() => archive(document)} className="min-h-10 rounded-full border border-line px-4 text-xs font-semibold text-ink">Archive</button>}</div></div><div className="mt-4 flex flex-wrap gap-3 text-[11px] text-ink-faint"><span>Source: {document.source || "secure document service"}</span>{document.visibility && <span>Visibility: {document.visibility}</span>}{document.file_size_bytes != null && <span>{Math.round(Number(document.file_size_bytes) / 1024)} KB</span>}</div></Card>)}</div>}
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4" role="dialog" aria-modal="true" aria-labelledby="document-details-title"><Card className="max-h-[85vh] w-full max-w-xl overflow-auto p-6"><div className="flex items-start justify-between gap-4"><div><h2 id="document-details-title" className="text-lg font-semibold text-ink">{selected.document.name}</h2><p className="mt-1 text-xs capitalize text-ink-faint">{selected.document.category} · {selected.document.status || "Status unavailable"}</p></div><button type="button" onClick={() => setSelected(null)} className="min-h-10 rounded-full border border-line px-4 text-xs font-semibold text-ink">Close</button></div>{detailsLoading ? <div className="mt-6 h-24 skeleton rounded-2xl" role="status" aria-label="Loading document history" /> : <><dl className="mt-6 grid grid-cols-2 gap-4 text-xs"><div><dt className="text-ink-faint">Created</dt><dd className="mt-1 font-semibold text-ink">{formatDate(selected.document.created_at)}</dd></div><div><dt className="text-ink-faint">Reference</dt><dd className="mt-1 break-all font-semibold text-ink">{selected.document.storage_ref || "Not available"}</dd></div></dl><h3 className="mt-6 font-semibold text-ink">Download history</h3>{selected.timeline?.length ? <ol className="mt-3 grid gap-3">{selected.timeline.map(event => <li key={event.id || `${event.event_type}-${event.created_at}`} className="flex justify-between gap-4 border-b border-line pb-3 text-xs"><span className="capitalize text-ink">{String(event.event_type || "document update").replaceAll("_", " ")}</span><span className="text-ink-faint">{formatDate(event.created_at)}</span></li>)}</ol> : <p className="mt-2 text-sm text-ink-muted">No document events are available yet.</p>}</>}</Card></div>}
  </InvestShell>;
}
