"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import InvestShell, { ButtonLink, Card, StatusPill } from "./InvestShell";
import TransactionTimeline from "./TransactionTimeline";
import { documentsApi, investApi, portfolioApi, sipApi } from "../../lib/invest/api";
import { ErrorCard, LoadingCards } from "./useInvestData";

const money = value => value == null ? "Not available" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value));
const number = value => value == null ? "Not available" : new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(Number(value));
const date = value => value ? new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "Date unavailable";
const returnTone = value => value == null ? "text-ink-faint" : Number(value) >= 0 ? "text-pos" : "text-neg";

function AllocationBars({ title, values }) {
  return <Card className="p-5"><h2 className="font-semibold text-ink">{title}</h2>{values?.length ? <div className="mt-5 grid gap-4">{values.slice(0, 6).map(item => <div key={item.name}><div className="flex justify-between gap-3 text-xs"><span className="truncate font-semibold text-ink">{item.name || "Unclassified"}</span><span className="shrink-0 text-ink-faint">{number(item.weight)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-surface-2"><div className="h-full rounded-full bg-accent" style={{ width: `${Math.min(100, Math.max(0, Number(item.weight) || 0))}%` }} /></div></div>)}</div> : <p className="mt-5 rounded-2xl bg-surface-2 p-4 text-sm leading-6 text-ink-muted">Allocation will appear once the portfolio contains resolved fund metadata.</p>}</Card>;
}

function HoldingRow({ holding, pendingStatus }) {
  const gain = holding.currentValue != null && holding.purchaseValue != null ? Number(holding.currentValue) - Number(holding.purchaseValue) : null;
  const folios = (holding.sources || []).map(source => source.folioNumber).filter(Boolean);
  const stale = Number(holding.staleDays) > 0;
  return <article className="rounded-2xl border border-line bg-surface p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words text-sm font-semibold text-ink">{holding.schemeName || holding.schemeCode || "Unnamed holding"}</h3><p className="mt-1 text-xs text-ink-faint">{holding.amc || "AMC unavailable"} · {holding.category || "Category unavailable"}</p></div>{pendingStatus ? <StatusPill status={pendingStatus} /> : <span className={`text-sm font-semibold ${returnTone(gain)}`}>{money(holding.currentValue)}</span>}</div><div className="mt-4 grid grid-cols-2 gap-3 text-xs sm:grid-cols-5"><div><div className="text-ink-faint">Units</div><div className="mt-1 font-semibold text-ink">{number(holding.units)}</div></div><div><div className="text-ink-faint">Invested</div><div className="mt-1 font-semibold text-ink">{money(holding.purchaseValue)}</div></div><div><div className="text-ink-faint">NAV</div><div className="mt-1 font-semibold text-ink">{money(holding.nav)}</div><div className={stale ? "mt-1 text-[10px] text-warn" : "mt-1 text-[10px] text-ink-faint"}>{holding.navDate ? `As of ${holding.navDate}` : "Date unavailable"}</div></div><div><div className="text-ink-faint">Weight</div><div className="mt-1 font-semibold text-ink">{number(holding.weight)}{holding.weight == null ? "" : "%"}</div></div><div><div className="text-ink-faint">Folio</div><div className="mt-1 truncate font-semibold text-ink">{folios[0] || "Not available"}</div></div></div>{stale && <p role="status" className="mt-4 rounded-2xl bg-warn/10 p-3 text-xs leading-5 text-warn">This holding uses an older NAV ({holding.staleDays} day{holding.staleDays === 1 ? "" : "s"} old). Current value may not reflect the latest market close.</p>}</article>;
}

export default function InvestPortfolio() {
  const [portfolio, setPortfolio] = useState(null); const [performance, setPerformance] = useState(null); const [history, setHistory] = useState([]); const [orders, setOrders] = useState([]); const [sips, setSips] = useState([]); const [documents, setDocuments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [optionalNotice, setOptionalNotice] = useState(false); const [connecting, setConnecting] = useState(false); const [pendingDetails, setPendingDetails] = useState([]);
  const load = useCallback(async () => { setLoading(true); setError(""); setOptionalNotice(false); try { const results = await Promise.allSettled([portfolioApi.getPortfolio(), portfolioApi.getPerformance(), portfolioApi.getHistory(20), investApi.getOrders(), sipApi.list(), documentsApi.list()]); const [combined, perf, timeline, orderResult, sipResult, documentResult] = results; if ([combined, perf, timeline].some(result => result.status === "rejected")) throw ([combined, perf, timeline].find(result => result.status === "rejected")?.reason || new Error("Portfolio data could not be loaded.")); setPortfolio(combined.value); setPerformance(perf.value); setHistory(timeline.value.events || []); setOrders(orderResult.status === "fulfilled" ? orderResult.value.orders || [] : []); setSips(sipResult.status === "fulfilled" ? sipResult.value.sips || [] : []); setDocuments(documentResult.status === "fulfilled" ? documentResult.value.documents || [] : []); setOptionalNotice([orderResult, sipResult, documentResult].some(result => result.status === "rejected")); } catch (e) { setError(e.message || "Portfolio data could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const active = orders.filter(order => ["submitted", "processing", "units_pending"].includes(order.status)).slice(0, 3); if (!active.length) { setPendingDetails([]); return; } Promise.all(active.map(order => investApi.getOrder(order.id).catch(() => ({ order, timeline: [] })))).then(setPendingDetails); }, [orders]);
  async function connect() { setConnecting(true); setError(""); try { await portfolioApi.connect(); await load(); } catch (e) { setError(e.message || "The portfolio could not be connected."); } finally { setConnecting(false); } }
  const summary = portfolio?.summary || {}; const holdings = portfolio?.holdings || []; const allocations = portfolio?.allocation || {}; const trend = useMemo(() => performance?.history || [], [performance]); const hasHoldings = holdings.length > 0; const maxHistory = useMemo(() => Math.max(...trend.map(item => Number(item.total_value) || 0), 1), [trend]);
  const pendingByScheme = useMemo(() => new Map(orders.filter(order => ["submitted", "processing", "units_pending"].includes(order.status)).map(order => [order.scheme_code, order.status])), [orders]);
  return <InvestShell title="Portfolio, with context." description="A source-aware view of holdings, allocation, performance and portfolio health. Every value comes from the Journey 3 portfolio service." actions={<><ButtonLink href="/portfolio" secondary>Import statement</ButtonLink>{!hasHoldings && <button type="button" onClick={connect} disabled={connecting} className="inline-flex min-h-11 items-center justify-center rounded-full bg-accent px-5 text-sm font-semibold text-white disabled:opacity-50">{connecting ? "Connecting…" : "Connect demo portfolio"}</button>}</>}>
    {loading ? <LoadingCards /> : error ? <ErrorCard message={error} retry={load} /> : <>
      {optionalNotice && <p className="mb-5 rounded-2xl border border-warn/25 bg-warn/10 p-4 text-sm text-warn" role="status">Some activity panels are temporarily unavailable. Portfolio values below remain sourced from the portfolio service.</p>}
      {!hasHoldings && <Card className="mb-5 border-accent/20 bg-accent/5 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-accent">Empty portfolio</div><h2 className="mt-2 text-lg font-semibold text-ink">Your portfolio is ready when you are.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-muted">Connect a clearly labelled demo portfolio to explore the experience, or import a real statement from the Portfolio Intelligence workspace.</p></div><StatusPill status="pending" /></div></Card>}
      <Card className="overflow-hidden p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{[["Current value", money(summary.totalValue), summary.totalValue == null ? "Unavailable" : "Latest server valuation"], ["Invested value", money(summary.investedValue), "Server cost basis"], ["Gain / loss", summary.gainLoss == null ? "Not available" : money(summary.gainLoss), summary.gainLossPct == null ? "Return unavailable" : `${number(summary.gainLossPct)}% absolute return`], ["XIRR", summary.xirr == null ? "Not available" : `${number(summary.xirr)}%`, "Annualized return"]].map(([label, value, detail]) => <div key={label} className="rounded-2xl bg-surface-2 p-4"><div className="text-xs text-ink-faint">{label}</div><div className={`mt-2 break-words text-2xl font-semibold tracking-[-.05em] ${label === "Gain / loss" ? returnTone(summary.gainLoss) : "text-ink"}`}>{value}</div><div className="mt-2 text-[11px] leading-4 text-ink-faint">{detail}</div></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Portfolio health", summary.healthScore, "/100"], ["Quality score", summary.qualityScore, "/100"], ["NAV coverage", summary.latestNavCoveragePct, "%"]].map(([label, value, suffix]) => <div key={label} className="rounded-2xl border border-line p-4"><div className="text-xs text-ink-faint">{label}</div><div className="mt-1 text-lg font-semibold text-ink">{value == null ? "Not available" : `${number(value)}${suffix}`}</div></div>)}</div>{portfolio?.dataQuality && <div role="status" className={`mt-5 rounded-2xl p-4 text-xs leading-5 ${portfolio.dataQuality.staleHoldingCount > 0 || portfolio.dataQuality.latestNavCoveragePct == null ? "bg-warn/10 text-warn" : "bg-surface-2 text-ink-muted"}`}><strong>Valuation freshness:</strong> {portfolio.dataQuality.latestNavCoveragePct == null ? "NAV coverage unavailable" : `${portfolio.dataQuality.latestNavCoveragePct}% of holdings have a current NAV`}{portfolio.dataQuality.staleHoldingCount > 0 ? ` · ${portfolio.dataQuality.staleHoldingCount} holding${portfolio.dataQuality.staleHoldingCount === 1 ? " uses" : "s use"} an older NAV` : " · no stale holdings reported"}{portfolio.dataQuality.navDateRange?.newest ? ` · latest holding NAV ${portfolio.dataQuality.navDateRange.newest}` : ""}</div>}</Card>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><AllocationBars title="Allocation by AMC" values={allocations.amc}/><AllocationBars title="Allocation by category" values={allocations.category}/></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold text-ink">Value history</h2><p className="mt-1 text-xs text-ink-faint">Official snapshots only · no estimated curve</p></div><StatusPill status={trend.length >= 3 ? "completed" : "pending"}/></div>{trend.length ? <div className="mt-6 flex h-40 items-end gap-2 overflow-x-auto border-b border-line">{trend.map(item => <div key={item.snapshot_date} className="flex h-full min-w-7 flex-1 flex-col justify-end gap-2"><div className="rounded-t-lg bg-accent/75" style={{ height: `${Math.max(4, (Number(item.total_value) || 0) / maxHistory * 100)}%` }} title={`${item.snapshot_date}: ${money(item.total_value)}`} /><span className="truncate text-[9px] text-ink-faint">{date(item.snapshot_date)}</span></div>)}</div> : <div className="mt-6 rounded-2xl bg-surface-2 p-5 text-sm leading-6 text-ink-muted">{performance?.historyNote || "No official portfolio snapshots yet."}</div>}</Card><Card className="p-5"><h2 className="font-semibold text-ink">Portfolio narrative</h2><p className="mt-3 text-sm leading-6 text-ink-muted">{portfolio?.bottomLine || "A portfolio health narrative will appear once the service has enough holdings and metadata to explain it."}</p><div className="mt-5 grid gap-3">{(portfolio?.strengths || []).slice(0, 2).map(value => <div key={value} className="rounded-2xl bg-pos/10 p-3 text-xs leading-5 text-pos">{value}</div>)}{(portfolio?.weaknesses || []).slice(0, 2).map(value => <div key={value} className="rounded-2xl bg-warn/10 p-3 text-xs leading-5 text-warn">{value}</div>)}</div></Card></div>
      <Card className="mt-5 p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-ink">Holdings</h2><span className="text-xs text-ink-faint">{holdings.length} consolidated scheme{holdings.length === 1 ? "" : "s"}</span></div><div className="mt-4 grid gap-3">{holdings.length ? holdings.map(holding => <HoldingRow key={holding.schemeCode || holding.schemeName} holding={holding} pendingStatus={pendingByScheme.get(holding.schemeCode)} />) : <p className="rounded-2xl bg-surface-2 p-5 text-sm leading-6 text-ink-muted">Holdings will appear after a statement import, completed order reconciliation or explicit demo connection.</p>}</div>{portfolio?.unresolved?.length > 0 && <p className="mt-4 rounded-2xl bg-warn/10 p-4 text-xs leading-5 text-warn">{portfolio.unresolved.length} holding{portfolio.unresolved.length === 1 ? "" : "s"} need review because fund metadata could not be resolved.</p>}</Card>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-ink">Pending transactions</h2><a href="/invest/transactions" className="text-xs font-semibold text-accent">View all →</a></div><div className="mt-4 grid gap-4">{pendingDetails.length ? pendingDetails.map(({ order, timeline }) => <TransactionTimeline key={order.id} currentStatus={order.status} reference={order.id} amount={order.amount} units={order.units} scheme={order.scheme_code} nextStep={order.status === "submitted" ? "Provider processing update" : "Units allotment update"} events={timeline || []} />) : <p className="rounded-2xl bg-surface-2 p-4 text-sm leading-6 text-ink-muted">No transactions are awaiting a provider update.</p>}</div></Card><Card className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-ink">Active SIPs</h2><a href="/invest/orders" className="text-xs font-semibold text-accent">Manage →</a></div>{sips.length ? <div className="mt-4 grid gap-3">{sips.slice(0, 4).map(sip => <div key={sip.id || `${sip.schemeCode}-${sip.startDate}`} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-line p-4"><div><div className="text-sm font-semibold text-ink">{sip.schemeName || sip.schemeCode || "SIP"}</div><div className="mt-1 text-xs text-ink-faint">{money(sip.amount)} · {sip.frequency || "Frequency unavailable"}</div></div><StatusPill status={sip.status || "active"}/></div>)}</div> : <p className="mt-4 rounded-2xl bg-surface-2 p-4 text-sm leading-6 text-ink-muted">Active SIPs will appear after a SIP mandate is created.</p>}</Card></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-ink">Documents</h2><a href="/invest/documents" className="text-xs font-semibold text-accent">Open vault →</a></div><p className="mt-3 text-sm text-ink-muted">{documents.length ? `${documents.length} document${documents.length === 1 ? "" : "s"} available in your vault.` : "Your statements, confirmations and tax documents will appear here."}</p></Card><Card className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-ink">Recent activity</h2><a href="/invest/transactions" className="text-xs font-semibold text-accent">View transactions →</a></div>{history.length ? <div className="mt-4 grid gap-3">{history.slice(0, 5).map((event, index) => <div key={`${event.occurredAt}-${index}`} className="border-b border-line pb-3 last:border-0"><div className="text-sm font-semibold text-ink">{event.label || "Portfolio update"}</div><div className="mt-1 text-xs text-ink-faint">{event.schemeCode || "Account"} · {event.occurredAt ? new Date(event.occurredAt).toLocaleString("en-IN") : "Time unavailable"}</div></div>)}</div> : <p className="mt-4 rounded-2xl bg-surface-2 p-4 text-sm text-ink-muted">Portfolio activity will appear as orders settle or statements are imported.</p>}</Card></div>
    </>}
  </InvestShell>;
}
