"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import InvestShell, { ButtonLink, Card, StatusPill } from "./InvestShell";
import { portfolioApi } from "../../lib/invest/api";
import { ErrorCard, LoadingCards } from "./useInvestData";

const money = (value) => value == null ? "Not available" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value));
const number = (value) => value == null ? "Not available" : new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(Number(value));
const returnTone = value => value == null ? "text-ink-faint" : Number(value) >= 0 ? "text-pos" : "text-neg";

function AllocationBars({ title, values }) {
  return <Card className="p-5"><h2 className="font-semibold text-ink">{title}</h2>{values?.length ? <div className="mt-5 grid gap-4">{values.slice(0, 6).map(item => <div key={item.name}><div className="flex items-center justify-between gap-3 text-xs"><span className="truncate font-semibold text-ink">{item.name || "Unclassified"}</span><span className="shrink-0 text-ink-faint">{number(item.weight)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-surface-2"><div className="h-full rounded-full bg-accent" style={{ width: `${Math.min(100, Math.max(0, Number(item.weight) || 0))}%` }} /></div></div>)}</div> : <p className="mt-5 rounded-2xl bg-surface-2 p-4 text-sm leading-6 text-ink-muted">Allocation will appear once the portfolio contains holdings with resolved fund metadata.</p>}</Card>;
}

function HoldingRow({ holding }) {
  return <article className="rounded-2xl border border-line bg-surface p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words text-sm font-semibold text-ink">{holding.schemeName || holding.schemeCode || "Unnamed holding"}</h3><p className="mt-1 text-xs text-ink-faint">{holding.amc || "AMC unavailable"} · {holding.category || "Category unavailable"}</p></div><span className={`text-sm font-semibold ${returnTone(holding.currentValue != null && holding.purchaseValue != null ? Number(holding.currentValue) - Number(holding.purchaseValue) : null)}`}>{money(holding.currentValue)}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs sm:grid-cols-4"><div><div className="text-ink-faint">Units</div><div className="mt-1 font-semibold text-ink">{number(holding.units)}</div></div><div><div className="text-ink-faint">Weight</div><div className="mt-1 font-semibold text-ink">{number(holding.weight)}{holding.weight == null ? "" : "%"}</div></div><div><div className="text-ink-faint">NAV</div><div className="mt-1 font-semibold text-ink">{money(holding.nav)}</div></div><div><div className="text-ink-faint">Sources</div><div className="mt-1 font-semibold text-ink">{holding.sources?.length || 0}</div></div></div></article>;
}

export default function InvestPortfolio() {
  const [portfolio, setPortfolio] = useState(null); const [performance, setPerformance] = useState(null); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [connecting, setConnecting] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [combined, perf, timeline] = await Promise.all([portfolioApi.getPortfolio(), portfolioApi.getPerformance(), portfolioApi.getHistory(20)]); setPortfolio(combined); setPerformance(perf); setHistory(timeline.events || []); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  async function connect() { setConnecting(true); setError(""); try { const value = await portfolioApi.connect(); setPortfolio(value); const [perf, timeline] = await Promise.all([portfolioApi.getPerformance(), portfolioApi.getHistory(20)]); setPerformance(perf); setHistory(timeline.events || []); } catch (e) { setError(e.message); } finally { setConnecting(false); } }
  const summary = portfolio?.summary || {};
  const holdings = portfolio?.holdings || [];
  const allocations = portfolio?.allocation || {};
  const trend = performance?.history || [];
  const hasHoldings = holdings.length > 0;
  const maxHistory = useMemo(() => Math.max(...trend.map(item => Number(item.total_value) || 0), 1), [trend]);
  return <InvestShell title="Portfolio, with context." description="A source-aware view of holdings, allocation, performance and portfolio health. Every value comes from the Journey 3 portfolio service." actions={<><ButtonLink href="/portfolio" secondary>Import statement</ButtonLink>{!hasHoldings && <button type="button" onClick={connect} disabled={connecting} className="inline-flex min-h-11 items-center justify-center rounded-full bg-accent px-5 text-sm font-semibold text-white disabled:opacity-50">{connecting ? "Connecting…" : "Connect demo portfolio"}</button>}</>}>
    {loading ? <LoadingCards /> : error ? <ErrorCard message={error} retry={load} /> : <>
      {!hasHoldings && <Card className="mb-5 border-accent/20 bg-accent/5 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-accent">Empty portfolio</div><h2 className="mt-2 text-lg font-semibold text-ink">Your portfolio is ready when you are.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-muted">Connect a clearly labelled demo portfolio to explore the experience, or import a real statement from the Portfolio Intelligence workspace.</p></div><StatusPill status="pending" /></div></Card>}
      <Card className="overflow-hidden p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{[["Current value",money(summary.totalValue),summary.totalValue==null?"Unavailable":"Latest server valuation"],["Invested value",money(summary.investedValue),"Server cost basis"],["Gain / loss",summary.gainLoss==null?"Not available":money(summary.gainLoss),summary.gainLossPct==null?"Return unavailable":`${number(summary.gainLossPct)}% absolute return`],["XIRR",summary.xirr==null?"Not available":`${number(summary.xirr)}%`,"Annualized return"]].map(([label,value,detail])=><div key={label} className="rounded-2xl bg-surface-2 p-4"><div className="text-xs text-ink-faint">{label}</div><div className={`mt-2 break-words text-2xl font-semibold tracking-[-.05em] ${label==="Gain / loss"?returnTone(summary.gainLoss):"text-ink"}`}>{value}</div><div className="mt-2 text-[11px] leading-4 text-ink-faint">{detail}</div></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-line p-4"><div className="text-xs text-ink-faint">Portfolio health</div><div className="mt-1 text-lg font-semibold text-ink">{summary.healthScore==null?"Not available":`${number(summary.healthScore)}/100`}</div></div><div className="rounded-2xl border border-line p-4"><div className="text-xs text-ink-faint">Quality score</div><div className="mt-1 text-lg font-semibold text-ink">{summary.qualityScore==null?"Not available":`${number(summary.qualityScore)}/100`}</div></div><div className="rounded-2xl border border-line p-4"><div className="text-xs text-ink-faint">NAV coverage</div><div className="mt-1 text-lg font-semibold text-ink">{summary.latestNavCoveragePct==null?"Not available":`${number(summary.latestNavCoveragePct)}%`}</div></div></div></Card>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><AllocationBars title="Allocation by AMC" values={allocations.amc}/><AllocationBars title="Allocation by category" values={allocations.category}/></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold text-ink">Value history</h2><p className="mt-1 text-xs text-ink-faint">Official snapshots only · no estimated curve</p></div><StatusPill status={trend.length >= 3 ? "completed" : "pending"}/></div>{trend.length ? <div className="mt-6 flex h-40 items-end gap-2 overflow-x-auto border-b border-line pb-0">{trend.map(item=><div key={item.snapshot_date} className="flex h-full min-w-7 flex-1 flex-col justify-end gap-2"><div className="rounded-t-lg bg-accent/75" style={{height:`${Math.max(4,(Number(item.total_value)||0)/maxHistory*100)}%`}} title={`${item.snapshot_date}: ${money(item.total_value)}`}/><span className="truncate text-[9px] text-ink-faint">{new Date(item.snapshot_date).toLocaleDateString("en-IN",{month:"short",day:"numeric"})}</span></div>)}</div> : <div className="mt-6 rounded-2xl bg-surface-2 p-5 text-sm leading-6 text-ink-muted">{performance?.historyNote || "No official portfolio snapshots yet."}</div>}</Card><Card className="p-5"><h2 className="font-semibold text-ink">Portfolio narrative</h2><p className="mt-3 text-sm leading-6 text-ink-muted">{portfolio?.bottomLine || "A portfolio health narrative will appear once the service has enough holdings and metadata to explain it."}</p><div className="mt-5 grid gap-3">{(portfolio?.strengths || []).slice(0,2).map(value=><div key={value} className="rounded-2xl bg-pos/10 p-3 text-xs leading-5 text-pos">{value}</div>)}{(portfolio?.weaknesses || []).slice(0,2).map(value=><div key={value} className="rounded-2xl bg-warn/10 p-3 text-xs leading-5 text-warn">{value}</div>)}</div></Card></div>
      <Card className="mt-5 p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-ink">Holdings</h2><span className="text-xs text-ink-faint">{holdings.length} consolidated scheme{holdings.length===1?"":"s"}</span></div><div className="mt-4 grid gap-3">{holdings.length ? holdings.map(holding=><HoldingRow key={holding.schemeCode || holding.schemeName} holding={holding}/>) : <p className="rounded-2xl bg-surface-2 p-5 text-sm leading-6 text-ink-muted">Holdings will appear after a statement import, completed order reconciliation or explicit demo connection.</p>}</div>{portfolio?.unresolved?.length>0&&<p className="mt-4 rounded-2xl bg-warn/10 p-4 text-xs leading-5 text-warn">{portfolio.unresolved.length} holding{portfolio.unresolved.length===1?"":"s"} need review because fund metadata could not be resolved.</p>}</Card>
      <Card className="mt-5 p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-ink">Portfolio timeline</h2><a href="/invest/transactions" className="text-xs font-semibold text-accent">View transactions →</a></div>{history.length ? <div className="mt-5 grid gap-0">{history.slice(0,6).map((event,index)=><div key={`${event.occurredAt}-${index}`} className="flex gap-3"><div className="flex flex-col items-center"><span className="grid h-7 w-7 place-items-center rounded-full bg-accent/10 text-xs font-bold text-accent">{index+1}</span>{index<history.slice(0,6).length-1&&<span className="h-7 w-px bg-line"/>}</div><div className="pb-4"><div className="text-sm font-semibold text-ink">{event.label || "Portfolio update"}</div><div className="mt-1 text-xs text-ink-faint">{event.schemeCode || "Account"} · {event.occurredAt ? new Date(event.occurredAt).toLocaleString("en-IN") : "Time unavailable"}</div></div></div>)}</div> : <p className="mt-5 rounded-2xl bg-surface-2 p-4 text-sm text-ink-muted">Portfolio activity will appear as orders settle or statements are imported.</p>}</Card>
    </>}
  </InvestShell>;
}
