"use client";

import { useEffect, useMemo, useState } from "react";
import InvestShell, { ButtonLink, Card, StatusPill } from "./InvestShell";
import { InvestApiError, notificationsApi } from "../../lib/invest/api";

const priorityTone = { high: "bg-neg/10 text-neg", medium: "bg-warn/10 text-warn", low: "bg-surface-2 text-ink-muted" };
const groupLabel = { compliance: "Readiness", order: "Orders", sip: "SIPs", advisor: "Advisor", system: "Account" };

function normalize(item) {
  return { ...item, id: item.id || item.notification_id, read: Boolean(item.read ?? item.is_read ?? item.read_at), priority: item.priority || "low", group: item.group || item.category || item.related_entity_type || "system", title: item.title || "Account update", body: item.body || item.message || "There is a new update in your secure workspace.", createdAt: item.createdAt || item.created_at || item.updated_at };
}

export default function NotificationsCenter() {
  const [items, setItems] = useState([]); const [filter, setFilter] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [syncing, setSyncing] = useState("");
  useEffect(() => { notificationsApi.list().then(value => setItems(Array.isArray(value.notifications) ? value.notifications.map(normalize) : [])).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => items.filter(item => filter === "all" || item.group === filter || (filter === "unread" && !item.read)), [filter, items]);
  async function markRead(item) { if (item.read || !item.id) return; setSyncing(item.id); try { await notificationsApi.markRead(item.id); setItems(current => current.map(value => value.id === item.id ? { ...value, read: true } : value)); } catch (e) { setError(e.message); } finally { setSyncing(""); } }
  const grouped = visible.reduce((acc, item) => { const key = item.group; (acc[key] ||= []).push(item); return acc; }, {});
  return <InvestShell title="Only what deserves attention." description="A calm inbox for readiness updates, orders, SIPs and advisor messages. Unread state stays synchronized with the server." actions={<ButtonLink href="/invest/compliance" secondary>Review readiness</ButtonLink>}>
    <div className="mb-5 flex gap-2 overflow-x-auto rounded-full border border-line bg-surface p-1" role="tablist" aria-label="Notification filters">{[["all","All"],["unread","Unread"],["compliance","Readiness"],["order","Orders"],["advisor","Advisor"]].map(([value,label]) => <button key={value} type="button" role="tab" aria-selected={filter === value} onClick={() => setFilter(value)} className={`min-h-10 shrink-0 rounded-full px-4 text-xs font-semibold ${filter === value ? "bg-ink text-bg" : "text-ink-muted hover:bg-surface-2"}`}>{label}{value === "unread" && items.filter(item => !item.read).length > 0 ? ` · ${items.filter(item => !item.read).length}` : ""}</button>)}</div>
    {loading ? <div className="grid gap-3">{[1,2,3].map(i => <div key={i} className="h-24 animate-pulse rounded-[1.5rem] bg-surface-2" />)}</div> : error && !(error instanceof InvestApiError && error.code === "not_found") ? <div role="alert" className="rounded-2xl bg-neg/10 p-4 text-sm text-neg">{error}<button type="button" onClick={() => window.location.reload()} className="ml-3 font-semibold underline">Retry</button></div> : visible.length === 0 ? <Card className="grid min-h-72 place-items-center p-7 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-accent/10 text-xl text-accent">◌</div><h2 className="mt-5 text-lg font-semibold text-ink">{error ? "Notifications are being connected" : filter === "unread" ? "You’re all caught up" : "No notifications yet"}</h2><p className="mt-2 max-w-md text-sm leading-6 text-ink-muted">{error ? "The server notification contract has not landed yet. This page is ready to consume it without a UI rewrite." : "Important readiness and investment events will appear here."}</p></div></Card> : <div className="grid gap-6">{Object.entries(grouped).map(([group, values]) => <section key={group} aria-labelledby={`notification-${group}`}><div id={`notification-${group}`} className="mb-2 text-[10px] font-bold uppercase tracking-[.16em] text-accent">{groupLabel[group] || group}</div><div className="grid gap-3">{values.map(item => <Card key={item.id || `${item.title}-${item.createdAt}`} className={`p-5 ${item.read ? "opacity-75" : "ring-1 ring-accent/20"}`}><div className="flex gap-4"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${item.read ? "bg-line-strong" : "bg-accent"}`} aria-label={item.read ? "Read" : "Unread"} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-semibold text-ink">{item.title}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-[.1em] ${priorityTone[item.priority] || priorityTone.low}`}>{item.priority} priority</span></div><p className="mt-2 text-sm leading-6 text-ink-muted">{item.body}</p><div className="mt-3 flex flex-wrap items-center gap-3 text-[11px] text-ink-faint"><span>{item.createdAt ? new Date(item.createdAt).toLocaleString("en-IN") : "Time unavailable"}</span>{!item.read && <button type="button" disabled={syncing === item.id} onClick={() => markRead(item)} className="font-semibold text-accent">{syncing === item.id ? "Saving…" : "Mark read"}</button>}{item.actionUrl && <a href={item.actionUrl} className="font-semibold text-accent">Open →</a>}</div></div></div></Card>)}</div></section>)}</div>}
  </InvestShell>;
}
