"use client";

import { useEffect, useState } from "react";
import InvestShell, { Card, StatusPill } from "./InvestShell";

const inputClass="mt-2 min-h-12 w-full rounded-2xl border border-line bg-bg px-4 text-sm text-ink outline-none focus:border-accent focus:ring-2 focus:ring-accent/15";
const stageOrder=["draft","submitted","processing","units_pending","completed"];
const labels={submitted:"Investment submitted",processing:"Sent for processing",units_pending:"Units allotment pending",completed:"Completed"};

export default function OrderCenter(){
  const [orders,setOrders]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [review,setReview]=useState(false); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({schemeCode:"",orderType:"purchase",amount:""});
  async function load(){try{const r=await fetch("/api/v1/invest/orders");const b=await r.json();if(!r.ok)throw new Error(b.error||"Orders could not load.");setOrders(b.orders||[]);setError("");}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const hasActiveOrders=orders.some(o=>["submitted","processing","units_pending"].includes(o.status));
  useEffect(()=>{if(!hasActiveOrders)return;const id=setInterval(load,6000);return()=>clearInterval(id)},[hasActiveOrders]);
  async function submit(){setSaving(true);setError("");try{const r=await fetch("/api/v1/invest/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,amount:Number(form.amount)})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Order was not accepted.");setReview(false);setForm({schemeCode:"",orderType:"purchase",amount:""});await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <InvestShell title="Every order, explained." description="Review a simulated mutual-fund order, submit it to the mock provider, and follow every status change." actions={<a href="/funds" className="inline-flex min-h-11 items-center rounded-full border border-line bg-surface px-5 text-sm font-semibold text-ink">Research funds</a>}>
    <div className="mb-5 rounded-2xl border border-information/20 bg-information/10 p-4 text-xs leading-5 text-ink-muted"><strong className="text-information">Mock investment environment.</strong> Orders are synthetic, payment is not collected, and no real units are purchased or redeemed.</div>
    <div className="grid gap-5 xl:grid-cols-[390px_minmax(0,1fr)]">
      <Card className="h-fit p-5 sm:p-6"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-accent">New order</div><h2 className="mt-2 text-xl font-semibold text-ink">{review?"Review before submitting":"Investment details"}</h2>
        {!review?<form onSubmit={e=>{e.preventDefault();setReview(true)}} className="mt-5 grid gap-5"><label className="text-xs font-semibold text-ink-muted">AMFI scheme code<input className={inputClass} value={form.schemeCode} onChange={e=>setForm({...form,schemeCode:e.target.value})} placeholder="For example: 120503" required/></label><label className="text-xs font-semibold text-ink-muted">Order type<select className={inputClass} value={form.orderType} onChange={e=>setForm({...form,orderType:e.target.value})}><option value="purchase">Purchase</option><option value="redemption">Redemption</option></select></label><label className="text-xs font-semibold text-ink-muted">Amount in rupees<input className={inputClass} type="number" min="1" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></label><button className="min-h-12 rounded-full bg-ink px-5 text-sm font-semibold text-bg">Review order</button></form>:
        <div className="mt-5"><dl className="grid gap-3 rounded-2xl bg-surface-2 p-4">{[["Scheme",form.schemeCode],["Type",form.orderType],["Amount",new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(form.amount))]].map(([k,v])=><div key={k} className="flex justify-between gap-4 text-sm"><dt className="text-ink-faint">{k}</dt><dd className="font-semibold capitalize text-ink">{v}</dd></div>)}</dl><p className="mt-4 text-xs leading-5 text-ink-muted">By submitting, you acknowledge this is a provider simulation. There is no payment step and no money movement.</p><div className="mt-5 flex gap-2"><button type="button" onClick={()=>setReview(false)} className="min-h-11 flex-1 rounded-full border border-line text-sm font-semibold text-ink">Edit</button><button type="button" onClick={submit} disabled={saving} className="min-h-11 flex-1 rounded-full bg-accent text-sm font-semibold text-white disabled:opacity-50">{saving?"Submitting…":"Submit mock order"}</button></div></div>}
        {error&&<p role="alert" className="mt-4 rounded-2xl bg-neg/10 p-4 text-xs leading-5 text-neg">{error}</p>}
      </Card>
      <div className="grid content-start gap-4"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-ink">Order history</h2><button type="button" onClick={load} className="min-h-10 rounded-full border border-line px-4 text-xs font-semibold text-ink">Refresh</button></div>{loading?<div className="h-44 animate-pulse rounded-[1.6rem] bg-surface-2"/>:orders.length===0?<Card className="grid min-h-64 place-items-center p-7 text-center"><div><div className="text-lg font-semibold text-ink">No investment orders yet</div><p className="mt-2 text-sm text-ink-muted">Your first mock order will appear here after the server accepts it.</p></div></Card>:orders.map(order=><Card key={order.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs text-ink-faint">{order.order_type?.replaceAll("_"," ")} · {order.scheme_code}</div><div className="mt-1 text-lg font-semibold text-ink">{order.amount?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(order.amount)):`${order.units} units`}</div></div><StatusPill status={order.status}/></div><div className="mt-5 grid grid-cols-5 gap-1" aria-label={`Order status: ${order.status}`}>{stageOrder.map((s,i)=>{const current=Math.max(0,stageOrder.indexOf(order.status));const done=i<=current;return <div key={s} className="min-w-0"><div className={`h-1.5 rounded-full ${done?"bg-accent":"bg-line"}`}/><div className="mt-2 hidden truncate text-[9px] text-ink-faint sm:block">{labels[s]||s}</div></div>})}</div>{order.rejection_reason&&<p className="mt-4 text-xs text-neg">{order.rejection_reason}</p>}</Card>)}</div>
    </div>
  </InvestShell>
}
