"use client";

import { useEffect, useState } from "react";
import InvestShell, { Card, StatusPill } from "./InvestShell";
import { investApi } from "../../lib/invest/api";
import { ORDER_LABELS as labels, ORDER_STAGES as stageOrder, ORDER_STATUS_META as statusMeta } from "../../lib/invest/transactionStatus";
import TransactionTimeline from "./TransactionTimeline";

const inputClass="mt-2 min-h-12 w-full rounded-2xl border border-line bg-bg px-4 text-sm text-ink outline-none focus:border-accent focus:ring-2 focus:ring-accent/15";

export default function OrderCenter(){
  const [orders,setOrders]=useState([]); const [loading,setLoading]=useState(true); const [apiReady,setApiReady]=useState(null); const [error,setError]=useState(""); const [review,setReview]=useState(false); const [saving,setSaving]=useState(false); const [draftOrder,setDraftOrder]=useState(null); const [confirmation,setConfirmation]=useState(null); const [selectedId,setSelectedId]=useState(""); const [detail,setDetail]=useState(null); const [detailLoading,setDetailLoading]=useState(false); const [detailError,setDetailError]=useState("");
  const [form,setForm]=useState({schemeCode:"",orderType:"purchase",amount:""});
  async function load(){try{const b=await investApi.getOrders();setOrders(b.orders||[]);setApiReady(true);setError("");}catch(e){setApiReady(false);setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const hasActiveOrders=orders.some(o=>["submitted","processing","units_pending"].includes(o.status));
  useEffect(()=>{if(!hasActiveOrders)return;const id=setInterval(load,6000);return()=>clearInterval(id)},[hasActiveOrders]);
  async function openDetails(item){setSelectedId(item.id);setDetailLoading(true);setDetailError("");try{setDetail(await investApi.getOrder(item.id))}catch(e){setDetailError(e.message)}finally{setDetailLoading(false)}}
  async function mutateOrder(action){setSaving(true);setError("");try{const result=await action();setOrders(current=>current.map(item=>item.id===result.order.id?result.order:item));if(selectedId===result.order.id)setDetail(current=>current?{...current,order:result.order}:current)}catch(e){setError(e.message)}finally{setSaving(false)}}
  async function prepareReview(event){event.preventDefault();setSaving(true);setError("");try{const result=await investApi.createOrder({...form,amount:Number(form.amount),draft:true});setDraftOrder(result.order);setReview(true);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
  async function submit(){setSaving(true);setError("");try{if(!draftOrder?.id)throw new Error("Review expired. Start the order again.");const result=await investApi.submitOrder(draftOrder.id);setConfirmation(result.order);setDraftOrder(null);setReview(false);setForm({schemeCode:"",orderType:"purchase",amount:""});await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
  async function editDraft(){setSaving(true);setError("");try{if(draftOrder?.id)await investApi.cancelOrder(draftOrder.id);setDraftOrder(null);setReview(false);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <InvestShell title="Every order, explained." description="Review a simulated mutual-fund order, submit it to the mock provider, and follow every status change." actions={<a href="/funds" className="inline-flex min-h-11 items-center rounded-full border border-line bg-surface px-5 text-sm font-semibold text-ink">Research funds</a>}>
    <div className="mb-5 rounded-2xl border border-information/20 bg-information/10 p-4 text-xs leading-5 text-ink-muted"><strong className="text-information">Provider simulation.</strong> The current contract does not collect payment or move money. The lifecycle below remains explicit so the UI is ready for the real provider contract.</div>
    {confirmation&&<TransactionTimeline currentStatus={confirmation.status} reference={confirmation.id} amount={confirmation.amount} scheme={confirmation.scheme_code} nextStep={confirmation.status==="submitted"?"Provider processing update":"Backend lifecycle update"} />}
    {confirmation?.distributor_arn&&<p className="-mt-3 mb-5 text-xs text-ink-faint">Distributor: ARN {confirmation.distributor_arn}{confirmation.distributor_euin?` / EUIN ${confirmation.distributor_euin}`:""}</p>}
    <div className="grid gap-5 xl:grid-cols-[390px_minmax(0,1fr)]">
      <Card className="h-fit p-5 sm:p-6"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-accent">New order</div><h2 className="mt-2 text-xl font-semibold text-ink">{review?"Review before submitting":"Investment details"}</h2>
        {!review?<form onSubmit={prepareReview} className="mt-5 grid gap-5"><label className="text-xs font-semibold text-ink-muted">AMFI scheme code<input className={inputClass} value={form.schemeCode} onChange={e=>setForm({...form,schemeCode:e.target.value})} placeholder="For example: 120503" required/></label><label className="text-xs font-semibold text-ink-muted">Order type<select className={inputClass} value={form.orderType} onChange={e=>setForm({...form,orderType:e.target.value})}><option value="purchase">Purchase</option><option value="redemption">Redemption</option></select></label><label className="text-xs font-semibold text-ink-muted">Amount in rupees<input className={inputClass} type="number" min="1" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></label><button disabled={!apiReady||saving} className="min-h-12 rounded-full bg-ink px-5 text-sm font-semibold text-bg disabled:cursor-not-allowed disabled:opacity-40">{saving?"Saving draft…":apiReady===null?"Checking order service…":apiReady?"Review order":"Order service unavailable"}</button></form>:
        <div className="mt-5"><div className="mb-4 rounded-2xl border border-accent/20 bg-accent/5 p-3 text-xs font-semibold text-accent">Draft saved on the server · {draftOrder?.id || "pending"}</div><dl className="grid gap-3 rounded-2xl bg-surface-2 p-4">{[["Scheme",form.schemeCode],["Type",form.orderType],["Amount",new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(form.amount))],...(draftOrder?.distributor_arn?[["Distributor",`ARN ${draftOrder.distributor_arn}${draftOrder.distributor_euin?` / EUIN ${draftOrder.distributor_euin}`:""}`]]:[])].map(([k,v])=><div key={k} className="flex justify-between gap-4 text-sm"><dt className="text-ink-faint">{k}</dt><dd className="font-semibold capitalize text-ink">{v}</dd></div>)}</dl><p className="mt-4 text-xs leading-5 text-ink-muted">By submitting, you acknowledge this is a provider simulation. There is no payment step and no money movement.</p><div className="mt-5 flex gap-2"><button type="button" onClick={editDraft} disabled={saving} className="min-h-11 flex-1 rounded-full border border-line text-sm font-semibold text-ink">Edit</button><button type="button" onClick={submit} disabled={saving} className="min-h-11 flex-1 rounded-full bg-accent text-sm font-semibold text-white disabled:opacity-50">{saving?"Submitting…":"Submit mock order"}</button></div></div>}
        {error&&<p role="alert" className="mt-4 rounded-2xl bg-neg/10 p-4 text-xs leading-5 text-neg">{error}</p>}
      </Card>
      <div className="grid content-start gap-4"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-ink">Order history</h2><button type="button" onClick={load} className="min-h-10 rounded-full border border-line px-4 text-xs font-semibold text-ink">Refresh</button></div>{loading?<div className="h-44 animate-pulse rounded-[1.6rem] bg-surface-2"/>:orders.length===0?<Card className="grid min-h-64 place-items-center p-7 text-center"><div><div className="text-lg font-semibold text-ink">No investment orders yet</div><p className="mt-2 text-sm text-ink-muted">Your first mock order will appear here after the server accepts it.</p></div></Card>:orders.map(order=>{const meta=statusMeta[order.status]||[order.status,"The provider returned an unknown state. Refresh to check again."];const current=Math.max(0,stageOrder.indexOf(order.status));return <Card key={order.id} className="p-5"><button type="button" onClick={()=>openDetails(order)} className="block w-full text-left"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs capitalize text-ink-faint">{order.order_type?.replaceAll("_"," ")} · {order.scheme_code}</div><div className="mt-1 text-lg font-semibold text-ink">{order.amount?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(order.amount)):`${order.units} units`}</div></div><StatusPill status={order.status}/></div><div className="mt-5 grid grid-cols-5 gap-1" aria-label={`Order status: ${order.status}`}>{stageOrder.map((s,i)=><div key={s} className="min-w-0"><div className={`h-1.5 rounded-full ${current>=i?"bg-accent":"bg-line"}`}/><div className="mt-2 hidden truncate text-[9px] text-ink-faint sm:block">{labels[s]}</div></div>)}</div><div className="mt-4 rounded-2xl bg-surface-2 p-3"><div className="flex items-center justify-between gap-3"><span className="text-sm font-semibold text-ink">{meta[0]}</span><span className="text-xs text-accent">View timeline →</span></div><p className="mt-1 text-xs leading-5 text-ink-muted">{meta[1]}</p></div>{order.rejection_reason&&<p className="mt-4 text-xs text-neg">{order.rejection_reason}</p>}</button>{(order.status==="retry_required"||order.status==="draft"||order.status==="submitted"||order.status==="processing")&&<div className="mt-4 flex justify-end gap-2 border-t border-line pt-4">{order.status==="retry_required"&&<button type="button" onClick={()=>mutateOrder(()=>investApi.retryOrder(order.id))} disabled={saving} className="min-h-10 rounded-full bg-accent px-4 text-xs font-semibold text-white">Retry order</button>}{["draft","submitted","processing"].includes(order.status)&&<button type="button" onClick={()=>mutateOrder(()=>investApi.cancelOrder(order.id))} disabled={saving} className="min-h-10 rounded-full border border-line px-4 text-xs font-semibold text-ink">Cancel</button>}</div>}</Card>})}
        {selectedId&&<Card className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-ink">Order timeline</h2><button type="button" onClick={()=>setSelectedId("")} className="text-xs font-semibold text-ink-muted">Close</button></div>{detailLoading?<div className="mt-4 h-20 animate-pulse rounded-2xl bg-surface-2"/>:detailError?<p role="alert" className="mt-4 rounded-2xl bg-neg/10 p-3 text-xs text-neg">{detailError}</p>:detail?.timeline?.length?<div className="mt-5 grid gap-0">{detail.timeline.map((event,index)=><div key={`${event.to_status}-${event.created_at}-${index}`} className="flex gap-3"><div className="flex flex-col items-center"><span className="grid h-7 w-7 place-items-center rounded-full bg-accent/10 text-xs font-bold text-accent">{index+1}</span>{index<detail.timeline.length-1&&<span className="h-8 w-px bg-line"/>}</div><div className="pb-4"><div className="text-sm font-semibold capitalize text-ink">{statusMeta[event.to_status]?.[0]||event.to_status?.replaceAll("_"," ")}</div><div className="mt-1 text-xs text-ink-faint">{event.created_at?new Date(event.created_at).toLocaleString("en-IN"):"Provider timestamp unavailable"}</div>{event.reason&&<div className="mt-1 text-xs text-neg">{event.reason}</div>}</div></div>)}</div>:<p className="mt-4 text-sm text-ink-muted">No provider timeline is available for this draft yet.</p>}</Card>}
      </div>
    </div>
  </InvestShell>
}
